#pragma once
#include <Arduino.h>

#define NO_ERROR 0

typedef enum
{
    RETURN_CODE__SUCCESS,
    RETURN_CODE__UNINITIALISED,
    RETURN_CODE__INVALID_PARAMETERS,

    RETURN_CODE__RTC__BEGIN_FAILED,
    RETURN_CODE__RTC__COMM_ERROR,
    RETURN_CODE__RTC__POWER_LOST,
    RETURN_CODE__RTC__WRITE_FAILED,
    RETURN_CODE__RTC__INVALID_TIMESTAMP_BUFFER,
    RETURN_CODE__RTC__LOCALTIME_FAILED,
    RETURN_CODE__RTC__TIMESTAMP_BUFFER_TOO_SMALL,


    RETURN_CODE__SD__FAILED_TO_OPEN_DIRECTORY,
    RETURN_CODE__SD__REACHED_EOF,
    RETURN_CODE__SD__STREAM_BUFFER_IS_FULL,
    RETURN_CODE__SD__FILE_READING_STOPPED_ERROR,
    RETURN_CODE__SD__WRONG_BYTES_COUNT_WRITTEN,
    RETURN_CODE__SD__NOT_A_DIRECTORY,
    RETURN_CODE__SD__CREATE_DIRECTORY_FAILED,
    RETURN_CODE__SD__REMOVE_DIRECTORY_FAILED,
    RETURN_CODE__SD__FAILED_TO_OPEN_FILE,
    RETURN_CODE__SD__FAILED_TO_OPEN_FILE_FOR_READING,
    RETURN_CODE__SD__FAILED_TO_OPEN_FILE_FOR_WRITING,
    RETURN_CODE__SD__FAILED_TO_OPEN_FILE_FOR_APPENDING,
    RETURN_CODE__SD__WRITE_FAILED,
    RETURN_CODE__SD__APPEND_FAILED,
    RETURN_CODE__SD__RENAME_FAILED,
    RETURN_CODE__SD__DELETE_FAILED,
    RETURN_CODE__SD__CARD_MOUNT_FAILED,
    RETURN_CODE__SD__NO_CARD_ATTACHED,
    RETURN_CODE__SD__UNKNOWN_CARD_TYPE,
    RETURN_CODE__SD__INVALID_FILE_STATE_FOR_ACTION,

    RETURN_CODE__BT__BEGIN_FAILED,
    RETURN_CODE__BT__ERR_NO_CLIENT,
    RETURN_CODE__BT__ERR_CONGESTED,
    RETURN_CODE__BT__ERR_TX_QUEUE_LOW,
    RETURN_CODE__BT__ERR_WRITE_FAILED
} return_code_e;